spring:
  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: cn.wenhe9.ggkt.*.entity
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-not-delete-value: 0
      logic-delete-value: 1
# 线程池相关参数配置
wenhe9:
  thread:
    core-size: 5
    max-size: 9
    keep-alive-time: 10