server:
  port: 8301
spring:
  profiles:
    include: [common]
    active: dev
  datasource:
    url: jdbc:mysql://bj-cdb-c504ejce.sql.tencentcdb.com:60161/glkt_vod?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '020921lhw'